CREATE TABLE books (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE,
    author VARCHAR(100) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    genre VARCHAR(255) CHECK (genre IN ('FICTION', 'FANTASY', 'SCIENCE_FICTION', 'MYSTERY', 'THRILLER', 'HORROR', 'ROMANCE', 'HISTORICAL_FICTION', 'LITERARY_FICTION', 'NON_FICTION', 'BIOGRAPHY_MEMOIR', 'HISTORY', 'SCIENCE', 'PHILOSOPHY', 'PSYCHOLOGY', 'SELF_HELP', 'BUSINESS_FINANCE', 'POLITICS', 'RELIGION_SPIRITUALITY', 'CLASSICS', 'POETRY', 'DRAMA', 'GRAPHIC_NOVEL', 'COOKBOOK', 'TRAVEL', 'ACADEMIC')),
    price NUMERIC(19, 2) NOT NULL
);